// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: new/entities/entities.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_new_entities_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_new_entities_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_new_entities_entities_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_new_entities_entities_proto protoreflect.FileDescriptor

const file_new_entities_entities_proto_rawDesc = "" +
	"\n" +
	"\x1bnew/entities/entities.proto\x12\fnew.entities\"@\n" +
	"\x12CreateOrderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB:Z8github.com/DenisEMPS/protos/api-go/new/entities;entitiesb\x06proto3"

var (
	file_new_entities_entities_proto_rawDescOnce sync.Once
	file_new_entities_entities_proto_rawDescData []byte
)

func file_new_entities_entities_proto_rawDescGZIP() []byte {
	file_new_entities_entities_proto_rawDescOnce.Do(func() {
		file_new_entities_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_new_entities_entities_proto_rawDesc), len(file_new_entities_entities_proto_rawDesc)))
	})
	return file_new_entities_entities_proto_rawDescData
}

var file_new_entities_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_new_entities_entities_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: new.entities.CreateOrderRequest
}
var file_new_entities_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_new_entities_entities_proto_init() }
func file_new_entities_entities_proto_init() {
	if File_new_entities_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_new_entities_entities_proto_rawDesc), len(file_new_entities_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_new_entities_entities_proto_goTypes,
		DependencyIndexes: file_new_entities_entities_proto_depIdxs,
		MessageInfos:      file_new_entities_entities_proto_msgTypes,
	}.Build()
	File_new_entities_entities_proto = out.File
	file_new_entities_entities_proto_goTypes = nil
	file_new_entities_entities_proto_depIdxs = nil
}
