// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: new/new.proto

package new

import (
	entities "github.com/DenisEMPS/protos/api-go/new/entities"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_new_new_proto protoreflect.FileDescriptor

const file_new_new_proto_rawDesc = "" +
	"\n" +
	"\rnew/new.proto\x12\x06new.v1\x1a\x1bnew/entities/entities.proto\x1a\x1bgoogle/protobuf/empty.proto2P\n" +
	"\x03New\x12I\n" +
	"\vCreateOrder\x12 .new.entities.CreateOrderRequest\x1a\x16.google.protobuf.Empty\"\x00B(Z&github.com/DenisEMPS/protos/api-go/newb\x06proto3"

var file_new_new_proto_goTypes = []any{
	(*entities.CreateOrderRequest)(nil), // 0: new.entities.CreateOrderRequest
	(*empty.Empty)(nil),                 // 1: google.protobuf.Empty
}
var file_new_new_proto_depIdxs = []int32{
	0, // 0: new.v1.New.CreateOrder:input_type -> new.entities.CreateOrderRequest
	1, // 1: new.v1.New.CreateOrder:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_new_new_proto_init() }
func file_new_new_proto_init() {
	if File_new_new_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_new_new_proto_rawDesc), len(file_new_new_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_new_new_proto_goTypes,
		DependencyIndexes: file_new_new_proto_depIdxs,
	}.Build()
	File_new_new_proto = out.File
	file_new_new_proto_goTypes = nil
	file_new_new_proto_depIdxs = nil
}
